module.exports = [
    {
      title: "Clean Up Gompers Park",
      BenefactorId: 1,
      CategoryId: 1,
      description: "Help your neighbors keep Gompers Park healthy and accessible this Earth day! Clean up tools and lunch will be provided.",
      photo_url: "https://res.cloudinary.com/dlfl6vj4n/image/upload/v1553106006/LLBTWFI-picture1.jpg",
      total_hours: 30,
      date: "4/21/2019",
      start_time: "9:00 AM",
      end_time: "12:00 PM",
      location: "Gompers Park Soccer Field"
    },
    {
      title: "Stock Shelves at Common Pantry",
      BenefactorId: 2,
      CategoryId: 2,
      description: "Come visit our pantry on Wednesday nights to stock shelves and help our clients shop for their favorite items.",
      photo_url: "https://res.cloudinary.com/dlfl6vj4n/image/upload/v1553106584/bazaar-bottles-business-15964.jpg",
      total_hours: 50,
      date: "5/20/2019",
      start_time: "6:00 PM",
      end_time: "8:00 PM",
      location: "Common Pantry North Center"
    },
    {
      title: "ESL and Literacy Tours Needed",
      BenefactorId: 3,
      CategoryId: 3,
      description: "Spend time conversing with our ESL learners and helping them through literacy exercises. Tutoring is needed every Thursday beginning at 6:00pm.",
      photo_url: "https://res.cloudinary.com/dlfl6vj4n/image/upload/v1553106249/senior-woman-learning-on-computer_4460x4460.jpg",
      total_hours: 40,
      date: "9/6/2019",
      start_time: "6:00 PM",
      end_time: "9:00 PM",
      location: "Albany Park Community Center"
    },
    {
      title: "Helping Hands Needed to Manage Flood-Damaged Items",
      BenefactorId: 4,
      CategoryId: 4,
      description: "Join forces with Chicago Cares and the Red Cross of Greater Chicago to help families remove flood-damaged furniture and flooring from their homes.",
      photo_url: "https://res.cloudinary.com/dlfl6vj4n/image/upload/v1553103716/collaboration-community-cooperation-461049.jpg",
      total_hours: 100,
      date: "4/28/2019",
      start_time: "10:00 AM",
      end_time: "5:00 PM",
      location: "Various"
    },
    {
      title: "Charm Our Residents with a Song",
      benefactorId: 5,
      categoryId: 5,
      description: "Musical therapy is a helps to improve memory and entertain our residents. Bring your instrument or just your voice and volunteer with Swedish Covenant",
      photo_url: "https://res.cloudinary.com/dlfl6vj4n/image/upload/v1553104848/action-adult-affection-339620.jpg",
      total_hours: 50,
      date: "4/2/2019",
      start_time: "11:00 AM",
      end_time: "12:30 PM",
      location: "Swedish Covenant Hospital"
    },
    {
      title: "Volunteer with Our Students",
      benefactorId: 6,
      categoryId: 6,
      description: "Assist our students in cooking projects to foster their autonomous spirits",
      photo_url: "https://res.cloudinary.com/dlfl6vj4n/image/upload/v1553107528/GettyImages-584219268.jpg",
      total_hours: 100,
      date: "4/15/2019",
      start_time: "3:00 PM",
      end_time: "4:00 PM",
      location: "Dorothy's Can-Do Cafe"
    },
    {
      title: "Prepare for Pet Portraits",
      benefactorId: 7,
      categoryId: 7,
      description: "Help Doggie Heaven wash and groom dogs for adoption portraits",
      photo_url: "https://res.cloudinary.com/dlfl6vj4n/image/upload/v1553105788/animal-black-and-white-close-up-37401.jpg",
      total_hours: 20,
      date: "4/30/2019",
      start_time: "1:00 PM",
      end_time: "3:00 PM",
      location: "Doggie Heaven"
    },
    {
      title: "Set Up Emergency Shelter",
      benefactorId: 8,
      categoryId: 8,
      description: "Visit us on any Friday night to help sleeping arrangements for our patrons.",
      photo_url: "https://res.cloudinary.com/dlfl6vj4n/image/upload/v1553105492/adult-beggar-begging-1058068.jpg",
      total_hours: 30,
      date: "4/12/2019",
      start_time: "7:00 PM",
      end_time: "9:00 PM",
      location: "St. Mark's Church"
    },
    {
      title: "Shovel Crew",
      benefactorId: 9,
      categoryId: 9,
      description: "Keep our communities safe from the elements and volunteer to shovel pathways with our team.",
      photo_url: "https://res.cloudinary.com/dlfl6vj4n/image/upload/v1553103816/charity-cheerful-community-1374360.jpg",
      total_hours: 10,
      date: "4/6/2019",
      start_time: "4:00 PM",
      end_time: "6:00 PM",
      location: "Chatham"
    },
    {
      title: "Share Your Web Dev Skills",
      benefactorId: 10,
      categoryId: 10,
      description: "Teach and learn alongside girls as they learn fundamental computer science concepts. Wednesday afternoons after school.",
      photo_url: "https://res.cloudinary.com/dlfl6vj4n/image/upload/v1553104008/adolescent-adult-back-view-710743.jpg",
      total_hours: 25,
      date: "4/10/2019",
      start_time: "3:00 PM",
      end_time: "4:00 PM",
      location: "Fuller School of Excellence"
    }
  ]